apiVersion: v1
kind: Service
metadata:
  name: {{ include "internal-service.fullname" . }}
  labels:
    {{- include "internal-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "internal-service.selectorLabels" . | nindent 4 }}
